---
title: "통계청 인구 격자 배분"
output: html_notebook
---

```{r}
library(foreach)
library(doParallel)
library(tidyverse)
library(data.table)

######### 병렬 처리 ##########
# 코어 개수 획득
numCores <- parallel::detectCores() - 1

# 클러스터 초기화
myCluster <- parallel::makeCluster(numCores)
doParallel::registerDoParallel(myCluster)

```



```{r}

folderRaw <- "d:/전국 건물 shape 파일 경로" #마지막에 슬래시를 붙이지 않는다.
folderWrite <- "d:/작업폴더/" #마지막에 슬래시를 넣는다.
src_folders <- list.dirs(folderRaw, recursive = FALSE) # list

loopSize <- length(src_folders)

sTime <- Sys.time()
result <- foreach::foreach(index = 1:loopSize,
                 .combine = rbind)  %dopar% {
                   
  library(sf)              
  library(data.table)  
  library(dplyr)                 
                   
  fileName <- paste0(src_folders[index],"/TL_SPBD_BULD.shp")
  print(paste0("read.....",fileName))
        
  bldg <- fileName %>% read_sf() #파일을 읽는다.
  bldgCoord <- as.data.table(st_coordinates(bldg)) #좌표들만 추출해서 table에 담는다.
  
  #250m 격자에 할당한다.
  gridTrue <- bldgCoord %>% mutate( xx = as.integer(X/250), yy = as.integer(Y/250) ) %>%
              distinct( gridx = xx, gridy = yy)           

  return(gridTrue)
}

# 클러스터 중지
parallel::stopCluster(myCluster)
eTime <- Sys.time()
print((eTime - sTime)*60)
rm(sTime)
rm(eTime)


uniqueGrid <- result %>%  distinct( gridx,gridy) %>%
               mutate( x = gridx*250, y = gridy*250)

fwrite(uniqueGrid, file=paste0(folderWrite,"bldgGrid_parallel.tsv"),
         quote=FALSE, sep = "\t", row.names = FALSE, col.names = TRUE)

rm(result)
rm(myCluster)
rm(loopSize)
rm(numCores)
rm(src_folders)
rm(folderRaw)
rm(uniqueGrid)
rm(folderWrite)

```



```{r}

library(Rcpp)
library(sf)

folderWrite <- "d:/작업폴더/" #마지막에 슬래시를 넣는다.

#Rcpp 파일 로드(별도로 설명한다)
sourceCpp("distributeValueToGrid.cpp")

#건물이 존재하는 250m 그리드를 읽는다. 바로 앞에서 저장한 파일
bldgGrid <- fread(paste0(folderWrite,"bldgGrid_parallel.tsv"),
                            sep = "\t", header = TRUE, stringsAsFactors = FALSE)

#Rcpp 변수에 입력한다. 추후 인구를 할당할 때 사용할 준비작업
bldgGridToSet(as.integer(bldgGrid$gridx), as.integer(bldgGrid$gridy))
rm(bldgGrid)

```


```{r}
##집계구 경계를 읽는다.

folderAdm <- "d:/집계구 경계 파일 경로/"
fileName <- paste0(folderAdm,"bnd_oa_00_2020_2020_2Q.shp")
system.time( admBndry <- fileName %>% read_sf())


#앞에서 읽은 집계구별 총 인구에 집계구를 join한다.
#집계구 도형 순서와 일치하는 집계구~인구 데이터프레임을 만드는 작업이다.
admCD <- as.data.frame(admBndry$TOT_REG_CD)
colnames(admCD) <- c("TOT_REG_CD")


#집계구 경계를 입력한다. 한번만 입력하면 된다.
admcoord <- admBndry %>% st_coordinates()
putAdmBoundary(admcoord[,1], admcoord[,2],
                  as.integer(admcoord[,3]), as.integer(admcoord[,4]),
                  as.integer(admcoord[,5]))
rm(admcoord)
rm(admBndry)

```



```{r}
#재분배 함수
distributePopulation <- function(fileName, admCD_) {
  
  
  
  # 통계청 집계구별 인구를 읽는다.
  system.time(popu <- fread(fileName,
                              sep = "^", header = TRUE, stringsAsFactors = FALSE,
                              colClasses = c('integer', 'character','character','character')))
  
  #집계구별 총 인구를 계산한다.
  #집계구별 인구 중 1~4인은 NA로 처리되어 있으므로 NA대신 2.5를 입력한다.
  popu <- popu %>% mutate(code = as.integer(substr(item,8, length(item)))) %>%
    filter(code<=21 | code == 999) %>% #21까지가 남녀인구 999는 자료없는 집계구
    mutate(popu = replace_na(as.numeric(value), 2.5)) %>%
    group_by(tot_oa_cd) %>%
    summarise(.groups="keep", popu = sum(popu)) %>%
    ungroup()
  

  #집계 확인
  print(paste0("인구 집계(파일 총계) :",sum(popu$popu)))
  
  #Rcpp 변수에 입력한다. 집계구 polygon의 일련번호와 일치하는 인구다.
  #뒤에서 그리드에 할당할 때 사용한다.
  admJoined <- admCD_ %>% left_join(., popu,
                         by=c("TOT_REG_CD"="tot_oa_cd"))
  putAdmPopu(admJoined$popu)
  rm(admJoined)
  rm(popu)
  
  
  numCores <- parallel::detectCores()-1
  result <- distributeValue(numCores)
  
  print(paste0("인구 집계(파일 총계) :",sum(result$value)))
   
  return(result)
}
```



```{r}
folderPopu <- "d:/집계구 인구 파일 경로/
fileName <- paste0(folderPopu, "2020년기준_2000년_성연령별인구.txt")

popuGrid50 <- distributePopulation(fileName, admCD)

fwrite(popuGrid50, file=paste0(folderWrite,"resultDistributed_50m_2000.tsv"),
         quote=FALSE, sep = "\t", row.names = FALSE, col.names = TRUE)



```



```{r}
#50m 그리드를 상위 그리드로 재집계 하는 함수
aggregatePopuGrid <- function(gridPopu, fromGrid, toGrid) {
  
  if (fromGrid >= toGrid) {
    print("그리드 설정 오류")
    return(NULL)
  }
  
  temp <- gridPopu %>% mutate(x = as.integer(as.integer(x/toGrid)*toGrid) + (toGrid/2) ,
                            y = as.integer(as.integer(y/toGrid)*toGrid) + (toGrid/2)) %>%
    group_by(x,y) %>%
    summarise(.groups="keep", value = sum(value)) %>%
    ungroup()
  
  return(temp)
  
}
```




```{r}
#인구를 재집계. 두번째 변수는 현재 그리드인데, 실수 확인용
system.time(popuGrid100 <- aggregatePopuGrid(popuGrid50, 50, 100))

sum(popuGrid100$value)

system.time(popuGrid250 <- aggregatePopuGrid(popuGrid50, 50, 250))

sum(popuGrid250$value)
```





```{r}

library(rmapshaper)

fileName <- paste0(folderAdm,"bnd_sigungu_00_2020_2020_2Q.shp")
system.time( sggBndry <- fileName %>% read_sf())

#맵 단순화. 그리드 중 특정 시군구 소속 경계를 추출하기 위함이므로 적당히 단순화시킨다.
#약 1분 가까이 걸린다.
system.time(sggSimple <- sggBndry %>% ms_simplify())

#정상적으로 읽고 변환되었는지 확인
ggplot() +
  geom_sf(data = sggSimple)

sggcoord <- sggSimple %>% st_coordinates()
sggcoord <- as.data.frame(sggcoord)

sggCode <- data.frame(as.integer(rownames(sggBndry)), sggSimple$sigungu_cd, sggSimple$sigungu_nm)
colnames(sggCode) <- c("index", "sggcode", "sggname")

sggcoord <- sggcoord %>% left_join(sggCode, by=c("L3"="index"))


rm(sggBndry)


```



```{r}
extractSggGrid <- function(popuGridData, sggCode, sggcoordData) {
  
  sggcoordExtracted <- sggcoordData %>% filter(sggcode==sggCode)
  
  popuGridFiltered <- filteringSggGrid(popuGridData$x, popuGridData$y,
                                       popuGridData$value, sggcoordExtracted$X,
                                       sggcoordExtracted$Y,sggcoordExtracted$L1,
                                       sggcoordExtracted$L2,sggcoordExtracted$L3)   
  return (popuGridFiltered)
}
```




```{r, fig.width = 12, fig.height = 12}


popuPart <- extractSggGrid(popuGrid250, "32030", sggcoord)

ggplot(data = popuPart %>% filter(value>1), aes(x=x, y=y, color = value)) +
  geom_point() +
  theme_bw() +
  #scale_size(range = c(1,8), breaks = c(0,1000,2000,3000, 4000, 5000, 6000, 7000))+
  #scale_colour_gradient2()+
  scale_color_continuous(low = "#ffcc11", high = "red", breaks = c(1000,4000,7000) ) +
  coord_fixed(ratio = 1)

ggsave(paste0(folderWrite,"강릉_2000.png"),
       antialias = "default", width = 240, height = 240, unit = c("mm"), dpi = 300)


popuShp <- st_as_sf(popuGrid250, coords = c("x", "y"), crs = 5179)
st_write(popuShp, paste0(folderWrite,"popu250.shp"), driver="ESRI Shapefile")

```






























